In [1]:
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

import pandas as pd
import numpy as np

In [2]:
## loading the data

hbn = Structure.from_file("..\\data\\h-BN.cif")

si = Structure.from_file("..\\data\\sillicon.cif")

c:\Users\Admin\anaconda3\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 2 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]


In [3]:
## basic structural properties

print("h-BN: Structure")
print(hbn)

print("\nSi: Structure")
print(si)

h-BN: Structure
Full Formula (B2 N2)
Reduced Formula: BN
abc   :   2.510000   2.510000   6.690000
angles:  90.000000  90.000000 120.000000
pbc   :       True       True       True
Sites (4)
  #  SP           a         b     c
---  ----  --------  --------  ----
  0  B3+   0.333333  0.666667  0.05
  1  B3+   0.666667  0.333333  0.95
  2  N3-   0         0         0
  3  N3-   0         0         0.5

Si: Structure
Full Formula (Si8)
Reduced Formula: Si
abc   :   5.430700   5.430700   5.430700
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (8)
  #  SP       a     b     c
---  ----  ----  ----  ----
  0  Si    0     0     0
  1  Si    0     0.5   0.5
  2  Si    0.5   0     0.5
  3  Si    0.5   0.5   0
  4  Si    0.75  0.75  0.25
  5  Si    0.75  0.25  0.75
  6  Si    0.25  0.75  0.75
  7  Si    0.25  0.25  0.25


In [4]:
## Composition analysis

print("h-BN: Composition")
print(hbn.composition)

print("\nSi: Composition")
print(si.composition)

h-BN: Composition
B3+2 N3-2

Si: Composition
Si8


In [5]:
## number of atoms

print("h-BN: Number of atoms", len(hbn))
print("Si: Number of atoms", len(si))   

h-BN: Number of atoms 4
Si: Number of atoms 8


In [6]:
## lattice parameters

print("h-BN: Lattice parameters")
print(hbn.lattice.abc)

print("\nSi: Lattice parameters")
print(si.lattice.abc)

h-BN: Lattice parameters
(2.51, 2.51, 6.69)

Si: Lattice parameters
(5.4307, 5.4307, 5.4307)


In [7]:
## lattice angles

print("h-BN: Lattice angles")
print(hbn.lattice.angles)

print("\nSi: Lattice angles")
print(si.lattice.angles)

h-BN: Lattice angles
(90.0, 90.0, 120.00000000000001)

Si: Lattice angles
(90.0, 90.0, 90.0)


In [8]:
## Unit cell volume 

print("h-BN: Unit cell volume", hbn.lattice.volume)
print("Si: Unit cell volume", si.lattice.volume)

h-BN: Unit cell volume 36.50095206429786
Si: Unit cell volume 160.164933272443


In [9]:
## density analysis

print("h-BN: Density")
print(hbn.density)

print("\nSi: Density")
print(si.density)

h-BN: Density
2.258064961053153 g cm^-3

Si: Density
2.329452224892313 g cm^-3


In [10]:
## Space group analysis

hbn_sga = SpacegroupAnalyzer(hbn)
si_sga = SpacegroupAnalyzer(si)


print("h-BN: Space group symbol")
print(hbn_sga.get_space_group_symbol())

print("\nSi: Space group symbol")
print(si_sga.get_space_group_symbol())

h-BN: Space group symbol
P-3m1

Si: Space group symbol
Fd-3m


In [11]:
##  Crystal system analysis

print("h-BN: Crystal system")
print(hbn_sga.get_crystal_system())

print("\nSi: Crystal system")
print(si_sga.get_crystal_system())

h-BN: Crystal system
trigonal

Si: Crystal system
cubic


In [12]:
## Site information

print("h-BN: Sites")

for i, site in enumerate(hbn):
    print(i,site)

h-BN: Sites
0 [1.57466632e-16 1.44914918e+00 3.34500000e-01] B3+
1 [1.255      0.72457459 6.3555    ] B3+
2 [0. 0. 0.] N3-
3 [0.    0.    3.345] N3-


In [13]:
print("\nSi sites")
for i, site in enumerate(si):
    print(i,site)


Si sites
0 [0. 0. 0.] Si
1 [4.36661584e-16 2.71535000e+00 2.71535000e+00] Si
2 [2.71535 0.      2.71535] Si
3 [2.71535000e+00 2.71535000e+00 3.32534469e-16] Si
4 [4.073025 4.073025 1.357675] Si
5 [4.073025 1.357675 4.073025] Si
6 [1.357675 4.073025 4.073025] Si
7 [1.357675 1.357675 1.357675] Si


In [14]:
## Bond length analysis

print("B-N bond lengths in h-BN")
print(hbn.get_distance(0, 2))

print("\nSi-Si bond lengths in Si")
print(si.get_distance(0, 1))

B-N bond lengths in h-BN
1.487253705099884

Si-Si bond lengths in Si
3.840084796589783


In [15]:
## nearest neighbor analysis of h-BN

neighbors_hbn = hbn.get_neighbors(hbn[0], 2.0)

print("h-BN neighbors:\n")


for n in neighbors_hbn:
    print(n)

h-BN neighbors:

[-1.255       0.72457459 -0.3345    ] B3+
[-1.25500000e+00  2.17372376e+00  1.53693173e-16] N3-
[0. 0. 0.] N3-
[ 1.255       0.72457459 -0.3345    ] B3+
[1.25500000e+00 2.17372376e+00 3.07386347e-16] N3-
[ 2.58311890e-16  2.89829835e+00 -3.34500000e-01] B3+


In [16]:
## nearest neighbor analysis of Si


neighbors_si = si.get_neighbors(si[0], 3.0)

print("Si neighbors:\n")
for n in neighbors_si:
    print(n)

Si neighbors:

[-1.357675 -1.357675  1.357675] Si
[-1.357675  1.357675 -1.357675] Si
[ 1.357675 -1.357675 -1.357675] Si
[1.357675 1.357675 1.357675] Si


In [17]:
## Coordination number

print("h-BN: Coordination number")
print(len(neighbors_hbn))

print("\nSi: Coordination number")
print(len(neighbors_si))

h-BN: Coordination number
6

Si: Coordination number
4


In [18]:
## Fractional coordinates of h-BN 

print("h-BN: Fractional coordinates")

for site in hbn:
    print(site.frac_coords)

h-BN: Fractional coordinates
[0.33333333 0.66666667 0.05      ]
[0.66666667 0.33333333 0.95      ]
[0. 0. 0.]
[0.  0.  0.5]


In [19]:
## Fractional coordinates of Si

print("\nSi: Fractional coordinates")

for site in si:
    print(site.frac_coords)


Si: Fractional coordinates
[0. 0. 0.]
[0.  0.5 0.5]
[0.5 0.  0.5]
[0.5 0.5 0. ]
[0.75 0.75 0.25]
[0.75 0.25 0.75]
[0.25 0.75 0.75]
[0.25 0.25 0.25]


In [20]:
## cartesian coordinates of h-BN

print("\nh-BN: Cartesian coordinates")

for site in hbn:
    print(site.coords)


h-BN: Cartesian coordinates
[1.57466632e-16 1.44914918e+00 3.34500000e-01]
[1.255      0.72457459 6.3555    ]
[0. 0. 0.]
[0.    0.    3.345]


In [21]:
## Cartesian coordinates of Si

print("\nSi: Cartesian coordinates")

for site in si:
    print(site.coords)


Si: Cartesian coordinates
[0. 0. 0.]
[4.36661584e-16 2.71535000e+00 2.71535000e+00]
[2.71535 0.      2.71535]
[2.71535000e+00 2.71535000e+00 3.32534469e-16]
[4.073025 4.073025 1.357675]
[4.073025 1.357675 4.073025]
[1.357675 4.073025 4.073025]
[1.357675 1.357675 1.357675]


In [22]:
## Structural comparision table 

comparison_data = {
    "Property": ["Composition",
                 "Number of atoms",
                "Lattice parameters (a,b,c)", 
                "Lattice angles (alpha, beta, gamma)",
                "Unit cell volume", 
                "Density",
                "Space group symbol", 
                "Crystal system",
                "Coordination number"],


    "h-BN": [hbn.composition.formula,
            len(hbn),
            hbn.lattice.abc,
            hbn.lattice.angles,
            hbn.lattice.volume,
            hbn.density,
            hbn_sga.get_space_group_symbol(),
            hbn_sga.get_crystal_system(),
            len(neighbors_hbn)],

    "Si": [si.composition.formula,
            len(si),
            si.lattice.abc,
            si.lattice.angles, 
            si.lattice.volume, si.density, 
            si_sga.get_space_group_symbol(), 
            si_sga.get_crystal_system(),
            len(neighbors_si)]
}

df = pd.DataFrame(comparison_data)

df

,Property,h-BN,Si
0,Composition,B2 N2,Si8
1,Number of atoms,4,8
2,"Lattice parameters (a,b,c)","(2.51, 2.51, 6.69)","(5.4307, 5.4307, 5.4307)"
3,"Lattice angles (alpha, beta, gamma)","(90.0, 90.0, 120.00000000000001)","(90.0, 90.0, 90.0)"
4,Unit cell volume,36.500952,160.164933
5,Density,2.258065,2.329452
6,Space group symbol,P-3m1,Fd-3m
7,Crystal system,trigonal,cubic
8,Coordination number,6,4


#### This structural analysis demonstrates clear crystallographic and geometric difference between h-BN and silicon. The comparison highlights how atomic arrangement,symmetry, and coordination influence material classification and structural behavior.